### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count

* Display the total number of players

In [2]:
summaryplr = pd.DataFrame(index=[0], columns=['Total Players'])
summaryplr['Total Players'] = purchase_data['SN'].nunique()
summaryplr

   Total Players
0            576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [3]:
summary = pd.DataFrame(index=[0], columns=['Unique Items' , 'Avg Price', 'Purchase','Total Revenue'])
summary['Unique Items'] = purchase_data['Item ID'].nunique()
summary['Avg Price'] = '$\$${:.2f}'.format(purchase_data['Price'].mean())
summary['Purchase'] = purchase_data['Purchase ID'].count()
summary['Total Revenue'] = '$\$${:.2f}'.format(purchase_data['Price'].sum())


summary

   Unique Items Avg Price  Purchase Total Revenue
0           183  $\$$3.05       780   $\$$2379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [4]:
uniquegengroup =  purchase_data.groupby('Gender').nunique()

gender_df = pd.DataFrame()
gender_df['Total Count'] = uniquegengroup["SN"]
gender_df['Percentage'] = (gender_df['Total Count'] / gender_df['Total Count'].sum()) * 100
gender_df['Percentage'] = gender_df["Percentage"].map("{0:.2f}%".format)

gender_df

                       Total Count Percentage
Gender
Female                          81     14.06%
Male                           484     84.03%
Other / Non-Disclosed           11      1.91%


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [5]:
#Calculates totals, counts, and unique counts off the purchase data
gentotal = purchase_data.groupby('Gender').sum()           
gencount = purchase_data.groupby('Gender').count()
genunique = purchase_data.groupby('Gender').nunique()

#Anaylsis slices are built off the sum,count, and nunique dataframes

GenderPurchaseAnalysis = pd.DataFrame()
GenderPurchaseAnalysis['purchase count'] = gencount['Purchase ID']

GenderPurchaseAnalysis['avg purchase'] = gentotal["Price"] / GenderPurchaseAnalysis['purchase count']
GenderPurchaseAnalysis['avg purchase'] = GenderPurchaseAnalysis['avg purchase'].map("$\$${:.2f}".format)

GenderPurchaseAnalysis['avg total'] = gentotal["Price"] / genunique["SN"]
GenderPurchaseAnalysis['avg total'] = GenderPurchaseAnalysis['avg total'].map("$\$${:.2f}".format)


GenderPurchaseAnalysis

                       purchase count avg purchase avg total
Gender
Female                            113     $\$$3.20  $\$$4.47
Male                              652     $\$$3.02  $\$$4.07
Other / Non-Disclosed              15     $\$$3.35  $\$$4.56

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [6]:
#establish bins for ages

bins = [0, 9, 14, 19, 24, 29, 34, 39, 100]
bin_names = ['<10', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40+']


#Categorize the existing players
agedemo = pd.DataFrame()
agedemo['AgeValues'] = purchase_data['Age']
agedemo['Age'] = pd.cut(agedemo['AgeValues'], bins, labels=bin_names)

agedemosum = pd.DataFrame(agedemo.groupby(agedemo['Age'], as_index=True).size())
agedemosum.columns = ['Total Count']


agedemosum['Percentage'] = (agedemosum['Total Count'] / agedemosum['Total Count'].sum()) * 100
agedemosum['Percentage'] = agedemosum["Percentage"].map("{0:.2f}%".format)

agedemosum

       Total Count Percentage
Age
<10             23      2.95%
10-14           28      3.59%
15-19          136     17.44%
20-24          365     46.79%
25-29          101     12.95%
30-34           73      9.36%
35-39           41      5.26%
40+             13      1.67%

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [10]:
#establish bins for ages

agebins = [0, 9, 14, 19, 24, 29, 34, 39, 100]
agebin_names = ['<10', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40+']

#Bin the purchase_data data frame by age
purchase_data['Age Ranges'] = pd.cut(purchase_data['Age'], agebins, labels=agebin_names)

purchase_data.groupby('Age Ranges').head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Ranges
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,35-39
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,35-39
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64,30-34
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,3.40,40+
24,24,Siala43,30,Male,141,Persuasion,3.19,30-34
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09,<10
30,30,Idai61,19,Male,140,Striker,2.94,15-19
31,31,Farusrian86,37,Male,179,"Wolf, Promise of the Moonwalker",4.48,35-39
32,32,Aeralria27,10,Male,133,Faith's Scimitar,4.09,10-14
33,33,Haillyrgue51,7,Male,44,Bonecarvin Battle Axe,2.38,<10
34,34,Sondim73,19,Male,160,Azurewrath,4.40,15-19
36,36,Idaisuir85,30,Male,76,Haunted Bronzed Bludgeon,3.15,30-34
37,37,Seuthep89,8,Male,73,Ritual Mace,2.05,<10
38,38,Reulae52,10,Female,116,Renewed Skeletal Katana,4.18,10-14
42,42,Aidaillodeu39,18,Male,72,Winter's Bite,3.77,15-19
46,46,Yasrisu92,27,Male,102,Avenger,3.44,25-29
49,49,Iaralrgue74,33,Male,110,Suspension,1.44,30-34
53,53,Ilosianya35,32,Male,176,Relentless Iron Skewer,2.84,30-34
54,54,Zhisrisu83,10,Male,25,Hero Cane,4.35,10-14
55,55,Phaelap26,25,Female,84,Arcane Gem,3.79,25-29
56,56,Raesty92,12,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,10-14
59,59,Yaliru88,19,Male,105,Hailstorm Shadowsteel Scythe,3.03,15-19
61,61,Jiskimya77,17,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,15-19
65,65,Chamirraya83,25,Male,34,Retribution Axe,2.22,25-29
70,70,Pheodai94,29,Male,143,Frenzied Scimitar,1.56,25-29
78,78,Haillyrgue51,7,Male,50,Dawn,4.60,<10
81,81,Heudai45,8,Female,174,Primitive Blade,3.47,<10
156,156,Eyrian71,40,Male,117,"Heartstriker, Legacy of the Light",1.79,40+
220,220,Jiskjask85,40,Male,46,Hopeless Ebon Dualblade,1.33,40+
248,248,Isursuir31,44,Male,137,"Aetherius, Boon of the Blessed",3.39,40+

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame